const items = [
    {
        id:'101',
        image:'img/1.jpg',
        company:'Carlton london',
        item_name:'Rhodium-plated CZ Floral Studs',
        original_price:1045,
        current_price:606,
        discount_percentage:45,
        return_period:14,
        delivery_date:'10 Oct 2023',
        rating:{
            stars:4.5,
            count:1400,
        },
    },
    { 
        id:'002',
        image:'img/2.jpg',
        company:'CUKOO',
        item_name:'Women padded Halter Neck Swimming Dress',
        original_price:2599,
        current_price:1507,
        discount_percentage:42,
        return_period:14,
        delivery_date:'10 oct 2023',
        rating:{
            stars:4.3,
            count:24,
        },
    },
    {
        id:'003',
        image:'img/3.jpg',
        company:'NUEVOSDAMAS',
        item_name:'Women Red & white Printed A-Line knee-Length Skirt',
        original_price:1599,
        current_price:550,
        discount_percentage:70,
        return_period:14,
        delivery_date:'10 Oct 2026',
        rating:{
            stars:4.1,
            count:249,
        },
    },
    {
        id:'004',
        image:'img/4.jpg',
        company:'ADIDAS',
        item_name:'Indian Cricket ODI Jersey',
        original_price:1001,
        current_price:1001,
        discount_percentage:0,
        return_period:14,
        delivery_date:'10 Oct 2026',
        rating:{
            stars:5.0,
            count:10,
        },
    },
    {
        id:'005',
        image:'img/5.jpg',
        company:'Roadster',
        item_name:'Pure Cotton T-shirt',
        original_price:1399,
        current_price:599,
        discount_percentage:65,
        return_period:14,
        delivery_date:'10 Oct 2026',
        rating:{
            stars:4.3,
            count:3500,
        },
    },
    {
        id:'006',
        image:'img/6.jpg',
        company:'Nike',
        item_name:'Men ReactX Running Shoes',
        original_price:14490,
        current_price:14490,
        discount_percentage:0,
        return_period:14,
        delivery_date:'10 Oct2026',
        rating:{
            stars:0.0,
            count:0,
        },
    },
    {
        id:'007',
        image:'img/7.jpg',
        company:'The India Garage Co',
        item_name:'Men Slim Fit Regular Shorts',
        original_price:1599,
        current_price:640,
        discount_percentage:60,
        rating:{
            stars:4.2,
            count:388,
        },
    },
    {
        id:'008',
        image:'img/8.jpg',
        company:'Nivea',
        item_name:'Men Fresh Deodrant 150ml',
        original_price:285,
        current_price:142,
        discount_percentage:50,
        return_period:14,
        delivery_date:'08 feb 2026',
        rating:{
            stars:4.2,
            count:5200,
        },
    },
]